version: '3.8'
volumes:
  pg_data:

services:
  db:
    image: postgres
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - pg_data://var/lib/postgresql/data

  app:
    build: .
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - db