"""Add discount field to sales

Revision ID: 4be518b3add5
Revises: dcde53913633
Create Date: 2025-03-23 03:29:08.950070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4be518b3add5'
down_revision: Union[str, None] = 'dcde53913633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale', sa.Column('discount', sa.Float(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE sale SET discount = random() * 50")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale', 'discount')
    # ### end Alembic commands ###
